#include<tuplestore/data_type_info.h>
#include<tuplestore/data_type_info_defaults.h>

data_type_info* BIT_FIELD_NULLABLE[65] = {
	NULL,
	&define_bit_field_nullable_type("", 1),
	&define_bit_field_nullable_type("", 2),
	&define_bit_field_nullable_type("", 3),
	&define_bit_field_nullable_type("", 4),
	&define_bit_field_nullable_type("", 5),
	&define_bit_field_nullable_type("", 6),
	&define_bit_field_nullable_type("", 7),
	&define_bit_field_nullable_type("", 8),
	&define_bit_field_nullable_type("", 9),
	&define_bit_field_nullable_type("", 10),
	&define_bit_field_nullable_type("", 11),
	&define_bit_field_nullable_type("", 12),
	&define_bit_field_nullable_type("", 13),
	&define_bit_field_nullable_type("", 14),
	&define_bit_field_nullable_type("", 15),
	&define_bit_field_nullable_type("", 16),
	&define_bit_field_nullable_type("", 17),
	&define_bit_field_nullable_type("", 18),
	&define_bit_field_nullable_type("", 19),
	&define_bit_field_nullable_type("", 20),
	&define_bit_field_nullable_type("", 21),
	&define_bit_field_nullable_type("", 22),
	&define_bit_field_nullable_type("", 23),
	&define_bit_field_nullable_type("", 24),
	&define_bit_field_nullable_type("", 25),
	&define_bit_field_nullable_type("", 26),
	&define_bit_field_nullable_type("", 27),
	&define_bit_field_nullable_type("", 28),
	&define_bit_field_nullable_type("", 29),
	&define_bit_field_nullable_type("", 30),
	&define_bit_field_nullable_type("", 31),
	&define_bit_field_nullable_type("", 32),
	&define_bit_field_nullable_type("", 33),
	&define_bit_field_nullable_type("", 34),
	&define_bit_field_nullable_type("", 35),
	&define_bit_field_nullable_type("", 36),
	&define_bit_field_nullable_type("", 37),
	&define_bit_field_nullable_type("", 38),
	&define_bit_field_nullable_type("", 39),
	&define_bit_field_nullable_type("", 40),
	&define_bit_field_nullable_type("", 41),
	&define_bit_field_nullable_type("", 42),
	&define_bit_field_nullable_type("", 43),
	&define_bit_field_nullable_type("", 44),
	&define_bit_field_nullable_type("", 45),
	&define_bit_field_nullable_type("", 46),
	&define_bit_field_nullable_type("", 47),
	&define_bit_field_nullable_type("", 48),
	&define_bit_field_nullable_type("", 49),
	&define_bit_field_nullable_type("", 50),
	&define_bit_field_nullable_type("", 51),
	&define_bit_field_nullable_type("", 52),
	&define_bit_field_nullable_type("", 53),
	&define_bit_field_nullable_type("", 54),
	&define_bit_field_nullable_type("", 55),
	&define_bit_field_nullable_type("", 56),
	&define_bit_field_nullable_type("", 57),
	&define_bit_field_nullable_type("", 58),
	&define_bit_field_nullable_type("", 59),
	&define_bit_field_nullable_type("", 60),
	&define_bit_field_nullable_type("", 61),
	&define_bit_field_nullable_type("", 62),
	&define_bit_field_nullable_type("", 63),
	&define_bit_field_nullable_type("", 64),
};

data_type_info* BIT_FIELD_NON_NULLABLE[65] = {
	NULL,
	&define_bit_field_non_nullable_type("", 1),
	&define_bit_field_non_nullable_type("", 2),
	&define_bit_field_non_nullable_type("", 3),
	&define_bit_field_non_nullable_type("", 4),
	&define_bit_field_non_nullable_type("", 5),
	&define_bit_field_non_nullable_type("", 6),
	&define_bit_field_non_nullable_type("", 7),
	&define_bit_field_non_nullable_type("", 8),
	&define_bit_field_non_nullable_type("", 9),
	&define_bit_field_non_nullable_type("", 10),
	&define_bit_field_non_nullable_type("", 11),
	&define_bit_field_non_nullable_type("", 12),
	&define_bit_field_non_nullable_type("", 13),
	&define_bit_field_non_nullable_type("", 14),
	&define_bit_field_non_nullable_type("", 15),
	&define_bit_field_non_nullable_type("", 16),
	&define_bit_field_non_nullable_type("", 17),
	&define_bit_field_non_nullable_type("", 18),
	&define_bit_field_non_nullable_type("", 19),
	&define_bit_field_non_nullable_type("", 20),
	&define_bit_field_non_nullable_type("", 21),
	&define_bit_field_non_nullable_type("", 22),
	&define_bit_field_non_nullable_type("", 23),
	&define_bit_field_non_nullable_type("", 24),
	&define_bit_field_non_nullable_type("", 25),
	&define_bit_field_non_nullable_type("", 26),
	&define_bit_field_non_nullable_type("", 27),
	&define_bit_field_non_nullable_type("", 28),
	&define_bit_field_non_nullable_type("", 29),
	&define_bit_field_non_nullable_type("", 30),
	&define_bit_field_non_nullable_type("", 31),
	&define_bit_field_non_nullable_type("", 32),
	&define_bit_field_non_nullable_type("", 33),
	&define_bit_field_non_nullable_type("", 34),
	&define_bit_field_non_nullable_type("", 35),
	&define_bit_field_non_nullable_type("", 36),
	&define_bit_field_non_nullable_type("", 37),
	&define_bit_field_non_nullable_type("", 38),
	&define_bit_field_non_nullable_type("", 39),
	&define_bit_field_non_nullable_type("", 40),
	&define_bit_field_non_nullable_type("", 41),
	&define_bit_field_non_nullable_type("", 42),
	&define_bit_field_non_nullable_type("", 43),
	&define_bit_field_non_nullable_type("", 44),
	&define_bit_field_non_nullable_type("", 45),
	&define_bit_field_non_nullable_type("", 46),
	&define_bit_field_non_nullable_type("", 47),
	&define_bit_field_non_nullable_type("", 48),
	&define_bit_field_non_nullable_type("", 49),
	&define_bit_field_non_nullable_type("", 50),
	&define_bit_field_non_nullable_type("", 51),
	&define_bit_field_non_nullable_type("", 52),
	&define_bit_field_non_nullable_type("", 53),
	&define_bit_field_non_nullable_type("", 54),
	&define_bit_field_non_nullable_type("", 55),
	&define_bit_field_non_nullable_type("", 56),
	&define_bit_field_non_nullable_type("", 57),
	&define_bit_field_non_nullable_type("", 58),
	&define_bit_field_non_nullable_type("", 59),
	&define_bit_field_non_nullable_type("", 60),
	&define_bit_field_non_nullable_type("", 61),
	&define_bit_field_non_nullable_type("", 62),
	&define_bit_field_non_nullable_type("", 63),
	&define_bit_field_non_nullable_type("", 64),
};

data_type_info* UINT_NULLABLE[9] = {
	NULL,
	&define_uint_nullable_type("", 1),
	&define_uint_nullable_type("", 2),
	&define_uint_nullable_type("", 3),
	&define_uint_nullable_type("", 4),
	&define_uint_nullable_type("", 5),
	&define_uint_nullable_type("", 6),
	&define_uint_nullable_type("", 7),
	&define_uint_nullable_type("", 8),
};

data_type_info* UINT_NON_NULLABLE[9] = {
	NULL,
	&define_uint_non_nullable_type("", 1),
	&define_uint_non_nullable_type("", 2),
	&define_uint_non_nullable_type("", 3),
	&define_uint_non_nullable_type("", 4),
	&define_uint_non_nullable_type("", 5),
	&define_uint_non_nullable_type("", 6),
	&define_uint_non_nullable_type("", 7),
	&define_uint_non_nullable_type("", 8),
};

data_type_info* INT_NULLABLE[9] = {
	NULL,
	&define_int_nullable_type("", 1),
	&define_int_nullable_type("", 2),
	&define_int_nullable_type("", 3),
	&define_int_nullable_type("", 4),
	&define_int_nullable_type("", 5),
	&define_int_nullable_type("", 6),
	&define_int_nullable_type("", 7),
	&define_int_nullable_type("", 8),
};

data_type_info* INT_NON_NULLABLE[9] = {
	NULL,
	&define_int_non_nullable_type("", 1),
	&define_int_non_nullable_type("", 2),
	&define_int_non_nullable_type("", 3),
	&define_int_non_nullable_type("", 4),
	&define_int_non_nullable_type("", 5),
	&define_int_non_nullable_type("", 6),
	&define_int_non_nullable_type("", 7),
	&define_int_non_nullable_type("", 8),
};

data_type_info* FLOAT_float_NULLABLE = &define_float_nullable_type("", float);
data_type_info* FLOAT_double_NULLABLE = &define_float_nullable_type("", double);
data_type_info* FLOAT_long_double_NULLABLE = &define_float_nullable_type("", long_double);

data_type_info* FLOAT_float_NON_NULLABLE = &define_float_non_nullable_type("", float);
data_type_info* FLOAT_double_NON_NULLABLE = &define_float_non_nullable_type("", double);
data_type_info* FLOAT_long_double_NON_NULLABLE = &define_float_non_nullable_type("", long_double);

data_type_info* LARGE_UINT_NULLABLE[33] = {
	NULL,
	&define_large_uint_nullable_type("", 1),
	&define_large_uint_nullable_type("", 2),
	&define_large_uint_nullable_type("", 3),
	&define_large_uint_nullable_type("", 4),
	&define_large_uint_nullable_type("", 5),
	&define_large_uint_nullable_type("", 6),
	&define_large_uint_nullable_type("", 7),
	&define_large_uint_nullable_type("", 8),
	&define_large_uint_nullable_type("", 9),
	&define_large_uint_nullable_type("", 10),
	&define_large_uint_nullable_type("", 11),
	&define_large_uint_nullable_type("", 12),
	&define_large_uint_nullable_type("", 13),
	&define_large_uint_nullable_type("", 14),
	&define_large_uint_nullable_type("", 15),
	&define_large_uint_nullable_type("", 16),
	&define_large_uint_nullable_type("", 17),
	&define_large_uint_nullable_type("", 18),
	&define_large_uint_nullable_type("", 19),
	&define_large_uint_nullable_type("", 20),
	&define_large_uint_nullable_type("", 21),
	&define_large_uint_nullable_type("", 22),
	&define_large_uint_nullable_type("", 23),
	&define_large_uint_nullable_type("", 24),
	&define_large_uint_nullable_type("", 25),
	&define_large_uint_nullable_type("", 26),
	&define_large_uint_nullable_type("", 27),
	&define_large_uint_nullable_type("", 28),
	&define_large_uint_nullable_type("", 29),
	&define_large_uint_nullable_type("", 30),
	&define_large_uint_nullable_type("", 31),
	&define_large_uint_nullable_type("", 32),
};

data_type_info* LARGE_UINT_NON_NULLABLE[33] = {
	NULL,
	&define_large_uint_non_nullable_type("", 1),
	&define_large_uint_non_nullable_type("", 2),
	&define_large_uint_non_nullable_type("", 3),
	&define_large_uint_non_nullable_type("", 4),
	&define_large_uint_non_nullable_type("", 5),
	&define_large_uint_non_nullable_type("", 6),
	&define_large_uint_non_nullable_type("", 7),
	&define_large_uint_non_nullable_type("", 8),
	&define_large_uint_non_nullable_type("", 9),
	&define_large_uint_non_nullable_type("", 10),
	&define_large_uint_non_nullable_type("", 11),
	&define_large_uint_non_nullable_type("", 12),
	&define_large_uint_non_nullable_type("", 13),
	&define_large_uint_non_nullable_type("", 14),
	&define_large_uint_non_nullable_type("", 15),
	&define_large_uint_non_nullable_type("", 16),
	&define_large_uint_non_nullable_type("", 17),
	&define_large_uint_non_nullable_type("", 18),
	&define_large_uint_non_nullable_type("", 19),
	&define_large_uint_non_nullable_type("", 20),
	&define_large_uint_non_nullable_type("", 21),
	&define_large_uint_non_nullable_type("", 22),
	&define_large_uint_non_nullable_type("", 23),
	&define_large_uint_non_nullable_type("", 24),
	&define_large_uint_non_nullable_type("", 25),
	&define_large_uint_non_nullable_type("", 26),
	&define_large_uint_non_nullable_type("", 27),
	&define_large_uint_non_nullable_type("", 28),
	&define_large_uint_non_nullable_type("", 29),
	&define_large_uint_non_nullable_type("", 30),
	&define_large_uint_non_nullable_type("", 31),
	&define_large_uint_non_nullable_type("", 32),
};

data_type_info* LARGE_INT_NULLABLE[33] = {
	NULL,
	&define_large_int_nullable_type("", 1),
	&define_large_int_nullable_type("", 2),
	&define_large_int_nullable_type("", 3),
	&define_large_int_nullable_type("", 4),
	&define_large_int_nullable_type("", 5),
	&define_large_int_nullable_type("", 6),
	&define_large_int_nullable_type("", 7),
	&define_large_int_nullable_type("", 8),
	&define_large_int_nullable_type("", 9),
	&define_large_int_nullable_type("", 10),
	&define_large_int_nullable_type("", 11),
	&define_large_int_nullable_type("", 12),
	&define_large_int_nullable_type("", 13),
	&define_large_int_nullable_type("", 14),
	&define_large_int_nullable_type("", 15),
	&define_large_int_nullable_type("", 16),
	&define_large_int_nullable_type("", 17),
	&define_large_int_nullable_type("", 18),
	&define_large_int_nullable_type("", 19),
	&define_large_int_nullable_type("", 20),
	&define_large_int_nullable_type("", 21),
	&define_large_int_nullable_type("", 22),
	&define_large_int_nullable_type("", 23),
	&define_large_int_nullable_type("", 24),
	&define_large_int_nullable_type("", 25),
	&define_large_int_nullable_type("", 26),
	&define_large_int_nullable_type("", 27),
	&define_large_int_nullable_type("", 28),
	&define_large_int_nullable_type("", 29),
	&define_large_int_nullable_type("", 30),
	&define_large_int_nullable_type("", 31),
	&define_large_int_nullable_type("", 32),
};

data_type_info* LARGE_INT_NON_NULLABLE[33] = {
	NULL,
	&define_large_int_non_nullable_type("", 1),
	&define_large_int_non_nullable_type("", 2),
	&define_large_int_non_nullable_type("", 3),
	&define_large_int_non_nullable_type("", 4),
	&define_large_int_non_nullable_type("", 5),
	&define_large_int_non_nullable_type("", 6),
	&define_large_int_non_nullable_type("", 7),
	&define_large_int_non_nullable_type("", 8),
	&define_large_int_non_nullable_type("", 9),
	&define_large_int_non_nullable_type("", 10),
	&define_large_int_non_nullable_type("", 11),
	&define_large_int_non_nullable_type("", 12),
	&define_large_int_non_nullable_type("", 13),
	&define_large_int_non_nullable_type("", 14),
	&define_large_int_non_nullable_type("", 15),
	&define_large_int_non_nullable_type("", 16),
	&define_large_int_non_nullable_type("", 17),
	&define_large_int_non_nullable_type("", 18),
	&define_large_int_non_nullable_type("", 19),
	&define_large_int_non_nullable_type("", 20),
	&define_large_int_non_nullable_type("", 21),
	&define_large_int_non_nullable_type("", 22),
	&define_large_int_non_nullable_type("", 23),
	&define_large_int_non_nullable_type("", 24),
	&define_large_int_non_nullable_type("", 25),
	&define_large_int_non_nullable_type("", 26),
	&define_large_int_non_nullable_type("", 27),
	&define_large_int_non_nullable_type("", 28),
	&define_large_int_non_nullable_type("", 29),
	&define_large_int_non_nullable_type("", 30),
	&define_large_int_non_nullable_type("", 31),
	&define_large_int_non_nullable_type("", 32),
};