#include<data_type_info.h>
#include<data_type_info_defaults.h>

data_type_info* BIT_FIELD_NULLABLE[65] = {
	NULL,
	&define_bit_field_nullable_type("BIT_FIELD", 1),
	&define_bit_field_nullable_type("BIT_FIELD", 2),
	&define_bit_field_nullable_type("BIT_FIELD", 3),
	&define_bit_field_nullable_type("BIT_FIELD", 4),
	&define_bit_field_nullable_type("BIT_FIELD", 5),
	&define_bit_field_nullable_type("BIT_FIELD", 6),
	&define_bit_field_nullable_type("BIT_FIELD", 7),
	&define_bit_field_nullable_type("BIT_FIELD", 8),
	&define_bit_field_nullable_type("BIT_FIELD", 9),
	&define_bit_field_nullable_type("BIT_FIELD", 10),
	&define_bit_field_nullable_type("BIT_FIELD", 11),
	&define_bit_field_nullable_type("BIT_FIELD", 12),
	&define_bit_field_nullable_type("BIT_FIELD", 13),
	&define_bit_field_nullable_type("BIT_FIELD", 14),
	&define_bit_field_nullable_type("BIT_FIELD", 15),
	&define_bit_field_nullable_type("BIT_FIELD", 16),
	&define_bit_field_nullable_type("BIT_FIELD", 17),
	&define_bit_field_nullable_type("BIT_FIELD", 18),
	&define_bit_field_nullable_type("BIT_FIELD", 19),
	&define_bit_field_nullable_type("BIT_FIELD", 20),
	&define_bit_field_nullable_type("BIT_FIELD", 21),
	&define_bit_field_nullable_type("BIT_FIELD", 22),
	&define_bit_field_nullable_type("BIT_FIELD", 23),
	&define_bit_field_nullable_type("BIT_FIELD", 24),
	&define_bit_field_nullable_type("BIT_FIELD", 25),
	&define_bit_field_nullable_type("BIT_FIELD", 26),
	&define_bit_field_nullable_type("BIT_FIELD", 27),
	&define_bit_field_nullable_type("BIT_FIELD", 28),
	&define_bit_field_nullable_type("BIT_FIELD", 29),
	&define_bit_field_nullable_type("BIT_FIELD", 30),
	&define_bit_field_nullable_type("BIT_FIELD", 31),
	&define_bit_field_nullable_type("BIT_FIELD", 32),
	&define_bit_field_nullable_type("BIT_FIELD", 33),
	&define_bit_field_nullable_type("BIT_FIELD", 34),
	&define_bit_field_nullable_type("BIT_FIELD", 35),
	&define_bit_field_nullable_type("BIT_FIELD", 36),
	&define_bit_field_nullable_type("BIT_FIELD", 37),
	&define_bit_field_nullable_type("BIT_FIELD", 38),
	&define_bit_field_nullable_type("BIT_FIELD", 39),
	&define_bit_field_nullable_type("BIT_FIELD", 40),
	&define_bit_field_nullable_type("BIT_FIELD", 41),
	&define_bit_field_nullable_type("BIT_FIELD", 42),
	&define_bit_field_nullable_type("BIT_FIELD", 43),
	&define_bit_field_nullable_type("BIT_FIELD", 44),
	&define_bit_field_nullable_type("BIT_FIELD", 45),
	&define_bit_field_nullable_type("BIT_FIELD", 46),
	&define_bit_field_nullable_type("BIT_FIELD", 47),
	&define_bit_field_nullable_type("BIT_FIELD", 48),
	&define_bit_field_nullable_type("BIT_FIELD", 49),
	&define_bit_field_nullable_type("BIT_FIELD", 50),
	&define_bit_field_nullable_type("BIT_FIELD", 51),
	&define_bit_field_nullable_type("BIT_FIELD", 52),
	&define_bit_field_nullable_type("BIT_FIELD", 53),
	&define_bit_field_nullable_type("BIT_FIELD", 54),
	&define_bit_field_nullable_type("BIT_FIELD", 55),
	&define_bit_field_nullable_type("BIT_FIELD", 56),
	&define_bit_field_nullable_type("BIT_FIELD", 57),
	&define_bit_field_nullable_type("BIT_FIELD", 58),
	&define_bit_field_nullable_type("BIT_FIELD", 59),
	&define_bit_field_nullable_type("BIT_FIELD", 60),
	&define_bit_field_nullable_type("BIT_FIELD", 61),
	&define_bit_field_nullable_type("BIT_FIELD", 62),
	&define_bit_field_nullable_type("BIT_FIELD", 63),
	&define_bit_field_nullable_type("BIT_FIELD", 64),
};

data_type_info* BIT_FIELD_NON_NULLABLE[65] = {
	NULL,
	&define_bit_field_non_nullable_type("BIT_FIELD", 1),
	&define_bit_field_non_nullable_type("BIT_FIELD", 2),
	&define_bit_field_non_nullable_type("BIT_FIELD", 3),
	&define_bit_field_non_nullable_type("BIT_FIELD", 4),
	&define_bit_field_non_nullable_type("BIT_FIELD", 5),
	&define_bit_field_non_nullable_type("BIT_FIELD", 6),
	&define_bit_field_non_nullable_type("BIT_FIELD", 7),
	&define_bit_field_non_nullable_type("BIT_FIELD", 8),
	&define_bit_field_non_nullable_type("BIT_FIELD", 9),
	&define_bit_field_non_nullable_type("BIT_FIELD", 10),
	&define_bit_field_non_nullable_type("BIT_FIELD", 11),
	&define_bit_field_non_nullable_type("BIT_FIELD", 12),
	&define_bit_field_non_nullable_type("BIT_FIELD", 13),
	&define_bit_field_non_nullable_type("BIT_FIELD", 14),
	&define_bit_field_non_nullable_type("BIT_FIELD", 15),
	&define_bit_field_non_nullable_type("BIT_FIELD", 16),
	&define_bit_field_non_nullable_type("BIT_FIELD", 17),
	&define_bit_field_non_nullable_type("BIT_FIELD", 18),
	&define_bit_field_non_nullable_type("BIT_FIELD", 19),
	&define_bit_field_non_nullable_type("BIT_FIELD", 20),
	&define_bit_field_non_nullable_type("BIT_FIELD", 21),
	&define_bit_field_non_nullable_type("BIT_FIELD", 22),
	&define_bit_field_non_nullable_type("BIT_FIELD", 23),
	&define_bit_field_non_nullable_type("BIT_FIELD", 24),
	&define_bit_field_non_nullable_type("BIT_FIELD", 25),
	&define_bit_field_non_nullable_type("BIT_FIELD", 26),
	&define_bit_field_non_nullable_type("BIT_FIELD", 27),
	&define_bit_field_non_nullable_type("BIT_FIELD", 28),
	&define_bit_field_non_nullable_type("BIT_FIELD", 29),
	&define_bit_field_non_nullable_type("BIT_FIELD", 30),
	&define_bit_field_non_nullable_type("BIT_FIELD", 31),
	&define_bit_field_non_nullable_type("BIT_FIELD", 32),
	&define_bit_field_non_nullable_type("BIT_FIELD", 33),
	&define_bit_field_non_nullable_type("BIT_FIELD", 34),
	&define_bit_field_non_nullable_type("BIT_FIELD", 35),
	&define_bit_field_non_nullable_type("BIT_FIELD", 36),
	&define_bit_field_non_nullable_type("BIT_FIELD", 37),
	&define_bit_field_non_nullable_type("BIT_FIELD", 38),
	&define_bit_field_non_nullable_type("BIT_FIELD", 39),
	&define_bit_field_non_nullable_type("BIT_FIELD", 40),
	&define_bit_field_non_nullable_type("BIT_FIELD", 41),
	&define_bit_field_non_nullable_type("BIT_FIELD", 42),
	&define_bit_field_non_nullable_type("BIT_FIELD", 43),
	&define_bit_field_non_nullable_type("BIT_FIELD", 44),
	&define_bit_field_non_nullable_type("BIT_FIELD", 45),
	&define_bit_field_non_nullable_type("BIT_FIELD", 46),
	&define_bit_field_non_nullable_type("BIT_FIELD", 47),
	&define_bit_field_non_nullable_type("BIT_FIELD", 48),
	&define_bit_field_non_nullable_type("BIT_FIELD", 49),
	&define_bit_field_non_nullable_type("BIT_FIELD", 50),
	&define_bit_field_non_nullable_type("BIT_FIELD", 51),
	&define_bit_field_non_nullable_type("BIT_FIELD", 52),
	&define_bit_field_non_nullable_type("BIT_FIELD", 53),
	&define_bit_field_non_nullable_type("BIT_FIELD", 54),
	&define_bit_field_non_nullable_type("BIT_FIELD", 55),
	&define_bit_field_non_nullable_type("BIT_FIELD", 56),
	&define_bit_field_non_nullable_type("BIT_FIELD", 57),
	&define_bit_field_non_nullable_type("BIT_FIELD", 58),
	&define_bit_field_non_nullable_type("BIT_FIELD", 59),
	&define_bit_field_non_nullable_type("BIT_FIELD", 60),
	&define_bit_field_non_nullable_type("BIT_FIELD", 61),
	&define_bit_field_non_nullable_type("BIT_FIELD", 62),
	&define_bit_field_non_nullable_type("BIT_FIELD", 63),
	&define_bit_field_non_nullable_type("BIT_FIELD", 64),
};

data_type_info* UINT_NULLABLE[9] = {
	NULL,
	&define_uint_nullable_type("UINT", 1),
	&define_uint_nullable_type("UINT", 2),
	&define_uint_nullable_type("UINT", 3),
	&define_uint_nullable_type("UINT", 4),
	&define_uint_nullable_type("UINT", 5),
	&define_uint_nullable_type("UINT", 6),
	&define_uint_nullable_type("UINT", 7),
	&define_uint_nullable_type("UINT", 8),
};

data_type_info* UINT_NON_NULLABLE[9] = {
	NULL,
	&define_uint_non_nullable_type("UINT", 1),
	&define_uint_non_nullable_type("UINT", 2),
	&define_uint_non_nullable_type("UINT", 3),
	&define_uint_non_nullable_type("UINT", 4),
	&define_uint_non_nullable_type("UINT", 5),
	&define_uint_non_nullable_type("UINT", 6),
	&define_uint_non_nullable_type("UINT", 7),
	&define_uint_non_nullable_type("UINT", 8),
};

data_type_info* INT_NULLABLE[9] = {
	NULL,
	&define_int_nullable_type("INT", 1),
	&define_int_nullable_type("INT", 2),
	&define_int_nullable_type("INT", 3),
	&define_int_nullable_type("INT", 4),
	&define_int_nullable_type("INT", 5),
	&define_int_nullable_type("INT", 6),
	&define_int_nullable_type("INT", 7),
	&define_int_nullable_type("INT", 8),
};

data_type_info* INT_NON_NULLABLE[9] = {
	NULL,
	&define_int_non_nullable_type("INT", 1),
	&define_int_non_nullable_type("INT", 2),
	&define_int_non_nullable_type("INT", 3),
	&define_int_non_nullable_type("INT", 4),
	&define_int_non_nullable_type("INT", 5),
	&define_int_non_nullable_type("INT", 6),
	&define_int_non_nullable_type("INT", 7),
	&define_int_non_nullable_type("INT", 8),
};

data_type_info* FLOAT_float_NULLABLE = &define_float_nullable_type("FLOAT", float);
data_type_info* FLOAT_double_NULLABLE = &define_float_nullable_type("FLOAT", double);
data_type_info* FLOAT_long_double_NULLABLE = &define_float_nullable_type("FLOAT", long_double);

data_type_info* FLOAT_float_NON_NULLABLE = &define_float_non_nullable_type("FLOAT", float);
data_type_info* FLOAT_double_NON_NULLABLE = &define_float_non_nullable_type("FLOAT", double);
data_type_info* FLOAT_long_double_NON_NULLABLE = &define_float_non_nullable_type("FLOAT", long_double);

data_type_info* LARGE_UINT_NULLABLE[33] = {
	NULL,
	&define_large_uint_nullable_type("LARGE_UINT", 1),
	&define_large_uint_nullable_type("LARGE_UINT", 2),
	&define_large_uint_nullable_type("LARGE_UINT", 3),
	&define_large_uint_nullable_type("LARGE_UINT", 4),
	&define_large_uint_nullable_type("LARGE_UINT", 5),
	&define_large_uint_nullable_type("LARGE_UINT", 6),
	&define_large_uint_nullable_type("LARGE_UINT", 7),
	&define_large_uint_nullable_type("LARGE_UINT", 8),
	&define_large_uint_nullable_type("LARGE_UINT", 9),
	&define_large_uint_nullable_type("LARGE_UINT", 10),
	&define_large_uint_nullable_type("LARGE_UINT", 11),
	&define_large_uint_nullable_type("LARGE_UINT", 12),
	&define_large_uint_nullable_type("LARGE_UINT", 13),
	&define_large_uint_nullable_type("LARGE_UINT", 14),
	&define_large_uint_nullable_type("LARGE_UINT", 15),
	&define_large_uint_nullable_type("LARGE_UINT", 16),
	&define_large_uint_nullable_type("LARGE_UINT", 17),
	&define_large_uint_nullable_type("LARGE_UINT", 18),
	&define_large_uint_nullable_type("LARGE_UINT", 19),
	&define_large_uint_nullable_type("LARGE_UINT", 20),
	&define_large_uint_nullable_type("LARGE_UINT", 21),
	&define_large_uint_nullable_type("LARGE_UINT", 22),
	&define_large_uint_nullable_type("LARGE_UINT", 23),
	&define_large_uint_nullable_type("LARGE_UINT", 24),
	&define_large_uint_nullable_type("LARGE_UINT", 25),
	&define_large_uint_nullable_type("LARGE_UINT", 26),
	&define_large_uint_nullable_type("LARGE_UINT", 27),
	&define_large_uint_nullable_type("LARGE_UINT", 28),
	&define_large_uint_nullable_type("LARGE_UINT", 29),
	&define_large_uint_nullable_type("LARGE_UINT", 30),
	&define_large_uint_nullable_type("LARGE_UINT", 31),
	&define_large_uint_nullable_type("LARGE_UINT", 32),
};

data_type_info* LARGE_UINT_NON_NULLABLE[33] = {
	NULL,
	&define_large_uint_non_nullable_type("LARGE_UINT", 1),
	&define_large_uint_non_nullable_type("LARGE_UINT", 2),
	&define_large_uint_non_nullable_type("LARGE_UINT", 3),
	&define_large_uint_non_nullable_type("LARGE_UINT", 4),
	&define_large_uint_non_nullable_type("LARGE_UINT", 5),
	&define_large_uint_non_nullable_type("LARGE_UINT", 6),
	&define_large_uint_non_nullable_type("LARGE_UINT", 7),
	&define_large_uint_non_nullable_type("LARGE_UINT", 8),
	&define_large_uint_non_nullable_type("LARGE_UINT", 9),
	&define_large_uint_non_nullable_type("LARGE_UINT", 10),
	&define_large_uint_non_nullable_type("LARGE_UINT", 11),
	&define_large_uint_non_nullable_type("LARGE_UINT", 12),
	&define_large_uint_non_nullable_type("LARGE_UINT", 13),
	&define_large_uint_non_nullable_type("LARGE_UINT", 14),
	&define_large_uint_non_nullable_type("LARGE_UINT", 15),
	&define_large_uint_non_nullable_type("LARGE_UINT", 16),
	&define_large_uint_non_nullable_type("LARGE_UINT", 17),
	&define_large_uint_non_nullable_type("LARGE_UINT", 18),
	&define_large_uint_non_nullable_type("LARGE_UINT", 19),
	&define_large_uint_non_nullable_type("LARGE_UINT", 20),
	&define_large_uint_non_nullable_type("LARGE_UINT", 21),
	&define_large_uint_non_nullable_type("LARGE_UINT", 22),
	&define_large_uint_non_nullable_type("LARGE_UINT", 23),
	&define_large_uint_non_nullable_type("LARGE_UINT", 24),
	&define_large_uint_non_nullable_type("LARGE_UINT", 25),
	&define_large_uint_non_nullable_type("LARGE_UINT", 26),
	&define_large_uint_non_nullable_type("LARGE_UINT", 27),
	&define_large_uint_non_nullable_type("LARGE_UINT", 28),
	&define_large_uint_non_nullable_type("LARGE_UINT", 29),
	&define_large_uint_non_nullable_type("LARGE_UINT", 30),
	&define_large_uint_non_nullable_type("LARGE_UINT", 31),
	&define_large_uint_non_nullable_type("LARGE_UINT", 32),
};